---
title: "Untitled"
author: "Amelia Ritger"
date: "2023-11-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(ggpmisc) #statpolyeq ggplot
```

# Population size
```{r}
alive <- read_csv(here("experiment", "data", "mortality.csv")) %>% #each file will be read in, specify which columns you need read in to avoid any error
  clean_names() %>%
  mutate(date = mdy(date)) #%>%
  #arrange(date) %>%
         #treatment = ifelse(tank < 6, "cold", ifelse(tank>10, "extreme", "severe")),
         #tank=as.factor(tank)) %>%
  #group_by(tank, genet) %>%
  #mutate(diff_n = n-lag(n, default = first(n))) %>%
  #ungroup()

#ggplot(alive, aes(x=date, y=diff_n)) +
#  geom_line(aes(color=genet)) +
#  facet_wrap(~tank)
```

# Behavior
```{r}
open <- read_csv(here("experiment", "data", "behavior.csv")) %>% #each file will be read in, specify which columns you need read in to avoid any error
  clean_names() %>%
  select(1:8) %>%
  mutate(date = mdy(date))
         #treatment = ifelse(tank < 6, "cold", ifelse(tank>10, "extreme", "severe")),
         #tank=as.factor(tank))
         #percent_open = open/n,
         #percent_closed = closed/n)

#ggplot(open, aes(x=date, y=percent_open, fill=genet)) +
#  geom_violin(position="dodge", alpha=0.5, outlier.colour="transparent") +
  #scale_fill_viridis(discrete=T, name="") +  #stat_poly_eq(use_label("eq")) +
  #geom_smooth(method = "lm", se = F) +
#  facet_wrap(~treatment)

#ggplot(open, aes(x=date, y=percent_closed, fill=genet)) +
#  geom_violin(position="dodge", alpha=0.5, outlier.colour="transparent") +
#  geom_point(aes(color=genet)) +
  #scale_fill_viridis(discrete=T, name="") +  #stat_poly_eq(use_label("eq")) +
  #geom_smooth(method = "lm", se = F) +
#  facet_wrap(~treatment)
```

# All data
```{r}
all <- full_join(open, alive, by=join_by(date==date, tank==tank, genet==genet)) %>%
  select(-time.y, -time.x) %>%
  mutate(treatment = factor(case_when(tank < 6 ~ "cold", tank > 10 ~ "extreme", TRUE ~ "severe"),
                            levels = c("cold", "severe", "extreme")),
         tank=as.factor(tank),
         value_replace = case_when(is.na(open) ~ n-(0+partial_open+partial_closed+closed),
                                   is.na(partial_open) ~ n-(open+0+partial_closed+closed),
                                   is.na(partial_closed) ~ n-(open+partial_open+0+closed),
                                   is.na(closed) ~ n-(open+partial_open+partial_closed+0),
                                   TRUE ~ n-(open+partial_open+partial_closed+closed)),
         across(open:closed, ~ ifelse(date < ymd("2023-09-30"), .x,
                                      ifelse(is.na(.x), value_replace, .x))),
        percent_open = (open+partial_open)/n,
        percent_closed = (closed+partial_closed)/n,
        #create a new column mhw where if the date is before 12/12/23, it's "during", and if it's after, it's "after"
        mhw = factor(case_when(date < ymd("2023-12-12") ~ "during", TRUE ~ "after"),
                     levels = c("during", "after"))) %>%
  group_by(tank, genet) %>%
  arrange(date) %>%
  mutate(removed_cum = cumsum(removed), # generate cumulative number of polyps removed, to represent total number of polyps excluding removal
         n_true = alive+dying_dead+removed_cum+floating, #overwrite n value to incorporate cumulative number of removed polyps
         diff_n = n_true-lag(n_true, default = first(n_true)),
         growth_rate = cumsum(diff_n)) %>%
  ungroup() %>%
  filter(!is.na(date))

ggplot(all, aes(x=genet, y=percent_closed, fill=genet, group=genet)) +
  geom_point(aes(color=genet)) +
  geom_violin(position="dodge", alpha=0.5, outlier.colour="transparent") +
  #facet_wrap(~treatment)
  facet_wrap(~mhw+treatment)

ggplot(all, aes(x=date, y=growth_rate, group=genet, color=genet)) +
  geom_point(alpha=0.5) +
  stat_poly_eq(use_label("eq")) +
  geom_smooth(method = "lm", se = F) +
  #facet_wrap(~treatment)
  facet_wrap(~mhw+treatment)

sample_anova <-aov(data=all,diff_n~genet+treatment)
summary(sample_anova)
TukeyHSD(sample_anova, which="genet")

#ggsave(here("experiment", "figures", "compare.png"), width=12, height=7)
```

