---
title: "MARSS"
author: "Amelia Ritger"
date: "2024-11-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MARSS)
```

## Load data
```{r}
source("mergeAllData.R", local = knitr::knit_global())
#Load temperature data AFTER you have run source(ReadRPiData)
weekly_temp <- read_csv(here("experiment", "data", "weekly_temperature.csv"))
```

## Prep data
```{r}
all_size <- all %>%
  filter(!is.na(avg_size)) %>%
  mutate(avg_size_log = log(avg_size)) %>%
  group_by(tank, genet) %>%
  mutate(avg_size_diff = avg_size_log - lag(avg_size_log),
         avg_size_diff2 = avg_size_diff - lag(avg_size_diff)) %>%
  ungroup()

all_size_marss <- all %>%
  filter(!is.na(avg_size)) %>%
  mutate(week = as.numeric(difftime(date, min(weekly_temp$friday), units = "weeks")) + 1,
         avg_size_log = log(avg_size),
         sd_size_log = log(sd_size),
         tank = as.numeric(tank)) %>%
  select(date, week, tank, mhw, genet, avg_size_log) %>%
  left_join(weekly_temp, by = c("date" = "friday", "tank"))

marss_data <- all_size_marss %>%
  mutate(genet_tank = paste(genet, tank, sep = "_"))

marss_data_wide <- marss_data %>%
  select(-date, -tank, -genet, -mhw, -treatment, -avg_temp, -min_temp, -max_temp) %>%
  pivot_wider(names_from = genet_tank, values_from = avg_size_log) %>%
  column_to_rownames(var = "week") %>%
  as.matrix() %>%
  t()

temp_cov <- weekly_temp %>%
  filter(friday < ymd("2024-02-16")) %>%
  arrange(friday, tank) %>%
  slice(rep(1:n(), each = 5)) %>%
  mutate(tank_rep = paste0(tank, letters[1:5][rep(1:5, times = n()/5)])) %>%
  select(tank_rep, friday, avg_temp) %>%
  pivot_wider(names_from = tank_rep, values_from = avg_temp) %>%
  mutate(week = row_number()) %>%
  select(-friday) %>%
  column_to_rownames(var = "week") %>%
  as.matrix() %>%
  t()

# Make blank temperature covariate interaction matrix
C_matrix <- matrix(0, nrow = 75, ncol = 75)
#Fill in interaction matrix
for (tank in 1:15) {
  start_row <- (tank - 1) * 5 + 1
  end_row <- start_row + 4  # 5 genotypes per tank
  for (i in start_row:end_row) {
    for (j in start_row:end_row) {
      C_matrix[i, j] <- tank
    }
  }
}
```

C matrix needs to be edited - all numeric matrix, ends up with 1 column - YES
c matrix = temp_cov
B = Identity, random walk - YES
Z = CUSTOM matrix, this is your MEAT - YES
A = A_matrix?
R = identity?
U = unequal?
Q = diangonal and equal?
```{r}

```

```{r}
C <- C_matrix #but try this with diagonal and unequal...
c <- temp_cov

fit <- MARSS(marss_data_wide, model = list(C=C, c=c))
```

