---
title: "Plotting SBC LTER data for MHWsim Methods Publication"
author: "Amelia Ritger"
date: "2022-08-05"
output: html_document
---

#Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(scales) #date_format for x axis plot
library(heatwaveR)
library(ggpubr) #combine multiple ggplots
library(data.table)
library(EDIutils)
library(xml2)
library(chron) #convert decimal time
library(ggpubr) #combine multiple ggplots
```

```{r}
source(here("experiment", "code", "r", "read_sbc_data.r"))
```

#HOBO data
## Download and format data
```{r}
mko_hobo <- read_sbc_data("Reef bottom water temperature - Bottom water temperature, all years") %>%
  clean_names() %>%
  mutate(year=format(date_local, '%Y'), #create only year column
         month=format(date_local, '%m')) %>% #create only month column
  unite("date_time", "date_local", "time_local", sep=" ", remove=FALSE) %>%
  mutate(date_time=ymd_hms(date_time)) %>% #apply lubridate to date and time
  arrange(date_time)

mko <- mko_hobo %>%
    filter(site %in% c("NAPL"))

max_mko <- max(mko$temp_c)
min_mko <- min(mko$temp_c)

#plot it up
ggplot(mko, aes(x = date_time, y = temp_c)) +
  geom_point() +
  labs(x = "Time", y = "Bottom Temperature") +
  scale_x_datetime(breaks = scales::date_breaks("9 months"),
                   labels = date_format("%b %Y")) +
  scale_y_continuous(limits = c(8, 24), breaks = seq(9, 24, by = 5)) +
  theme_classic()
```

## Assess MHW
```{r}
# Reformat df to run heatwaveR
mko_heatwaver <- mko %>%
  group_by(date_local) %>%
  summarize(temp_c=mean(temp_c)) %>%
  mutate(date=as.Date(date_local)) %>%
  rename(t=date_local,
         temp=temp_c) %>%
  select(t, temp)

#identify start and end dates of df
head(mko_heatwaver)
tail(mko_heatwaver)

mhw_start_date <- "2002-08-16"
mhw_end_date <- "2023-06-26"

# Detect the events in a time series
ts <- heatwaveR::ts2clm(mko_heatwaver, x=t, y=temp, climatologyPeriod = c(mhw_start_date, mhw_end_date))
mhw <- heatwaveR::detect_event(ts)

#identify MHW events
mhw$event %>%
   dplyr::ungroup() %>%
   dplyr::select(event_no, duration, date_start, date_peak, date_end, intensity_max, intensity_mean, intensity_cumulative) %>%
   dplyr::arrange(-duration)

#identify dates of interest
climatology <- mhw$climatology %>%
  arrange(t)
  
mhw_start <- which(climatology$t == "2014-01-01")[1]
mhw_end <- which(climatology$t == "2016-02-29")[1]

#subset for dates of interest
mko_mhw <- mhw$climatology %>%
  slice(mhw_start:mhw_end)

#plot clean ribbon
ggplot(mko_mhw, aes(x = t, ymax = pmax(thresh, temp), ymin = thresh)) +
  geom_line(aes(y = seas, colour = "seas"), size = 0.8) +
  geom_ribbon(fill = "red") +
  geom_line(aes(y = thresh, colour = "thresh"), size = 0.8) +
  geom_line(aes(y = temp, colour = "temp"), alpha=0.3) +
  #geom_text(size = 12, colour = "black", aes(x = as.Date("2014-02-01"), y = 24, label = "MKO")) +
  #geom_line(aes(y = seas, colour = "seas"), size = 0.8, linetype="dashed") +
  scale_colour_manual(name = "Line Colour",
                      values = c("seas" = "dodgerblue4",
                                 "temp" = "black", 
                                 "thresh" =  "chartreuse4"),
                      labels= c("Climatology", "Temperature", "Threshold")) +
  scale_x_date(date_labels = "%b %Y",
               breaks = scales::date_breaks("6 months"),
               expand=c(0,0),
               limits = c(min(mko_mhw$t), 
                         max = max(mko_mhw$t))) +
  scale_y_continuous(limits = c(11, 26), breaks = seq(11, 26, by = 2)) +
  guides(colour = guide_legend(override.aes = list(fill = NA))) +
  labs(y = expression(paste("Temperature (", degree, "C)")),
       x = "Date") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, vjust = 1, hjust=1, size=14),
        axis.text.y=element_text(size=14),
        axis.title.x=element_text(size=18),
        axis.title.y=element_text(size=18),
        legend.text=element_text(size=12),
        legend.position="top",
        legend.title = element_blank())

#ggsave(here("experiment", "figures", "mhw_hoboNAP.png"), width = 20, height = 7)
```

#ADCP data
## Download and format data
```{r}
adcp <- read_sbc_data("Moored CTD and ADCP: NAP - Moored CTD and ADCP at Naples Reef NAP") %>%
  clean_names() %>%
  select(year, month, day, decimal_time, temp_adcp, temp_top, temp_mid, temp_bot) %>%
  mutate(date=ymd(paste(year, month, day)),
         time=format(times(decimal_time))) %>%
  unite(date_time, c(date, time), sep = " ", remove = FALSE) %>% # combine the date and time columns
  mutate(date_time=ymd_hms(date_time)) %>%
  arrange(date_time)
```

## Assess MHW
```{r}
# Reformat df to run heatwaveR
adcp_heatwaver <- adcp %>%
  group_by(date) %>%
  filter(!is.na(temp_adcp)) %>%
  summarize(temp_c=mean(temp_adcp)) %>%
  mutate(date=as.Date(date)) %>%
  rename(t=date,
         temp=temp_c) %>%
  select(t, temp)

#identify start and end dates of df
mhw_start_date <- adcp_heatwaver$t[1]
mhw_end_date <- adcp_heatwaver$t[nrow(adcp_heatwaver)]
```

### Detect MHW events and plot
```{r}
# Detect the events in a time series
ts <- heatwaveR::ts2clm(adcp_heatwaver, x=t, y=temp, climatologyPeriod = c(mhw_start_date, mhw_end_date))
mhw <- heatwaveR::detect_event(ts)

# identify MHW events
mhw$event %>%
   dplyr::ungroup() %>%
   dplyr::select(event_no, duration, date_start, date_peak, date_end, intensity_max, intensity_mean, intensity_cumulative) %>%
   dplyr::arrange(-duration)

#identify dates of interest
climatology <- mhw$climatology %>%
  arrange(t)
  
mhw_start <- which(climatology$t == "2018-01-01")[1]
mhw_end <- which(climatology$t == "2019-01-01")[1]

#subset for dates of interest
mko_mhw <- mhw$climatology %>%
  slice(mhw_start:mhw_end)

#plot clean ribbon
#y <- 
ggplot(mko_mhw, aes(x = t, ymax = pmax(thresh, temp), ymin = thresh)) +
    annotate("rect", xmin=ymd("2018-07-01"), xmax=ymd("2018-07-31"), ymin=-Inf, ymax=Inf, alpha=0.2,fill="#999999") + #or use ymin ymax -Inf Inf
  geom_line(aes(y = seas, colour = "seas"), size = 0.8) +
  geom_ribbon(fill = "#D55E00") +
  geom_line(aes(y = thresh, colour = "thresh"), size = 0.8) +
  geom_line(aes(y = temp, colour = "temp"), alpha=0.5, size=0.7) +
  #geom_text(size = 12, colour = "black", aes(x = as.Date("2014-02-01"), y = 24, label = "MKO")) +
  #geom_line(aes(y = seas, colour = "seas"), size = 0.8, linetype="dashed") +
  scale_colour_manual(name = "Line Colour",
                      values = c("seas" = "#0072B2",
                                 "temp" = "#000000", 
                                 "thresh" =  "#009E73"),
                      labels= c("Climatology", "Temperature", "Threshold")) +
  scale_x_date(date_labels = "%b %Y",
               breaks = scales::date_breaks("3 months"),
               expand=c(0,0),
               limits = c(min(mko_mhw$t),
                          max(mko_mhw$t))) +
  #start the x axis tick labels at Jan 1 2018
  scale_y_continuous(limits = c(10, 19), breaks = seq(10, 19, by = 2)) +
  guides(colour = guide_legend(override.aes = list(fill = NA))) +
  labs(y = expression(paste("Temperature (", degree, "C)")),
       x = "Date") +
  theme_bw() +
  #add 1 inch white space to right of graph
  theme(axis.text.x=element_text(angle=45, vjust = 1, hjust=1, size=14),
        axis.text.y=element_text(size=14),
        axis.title.x=element_text(size=18),
        axis.title.y=element_text(size=18),
        legend.text=element_text(size=12),
        legend.position="top",
        legend.title = element_blank(),
        plot.margin = unit(c(0, 0.6, 0, 0.5), "cm"))

#ggsave(here("experiment", "figures", "mhw_year.png"), width=12, height=6)
```

Plot daily variation
```{r}
adcp_daily <- adcp %>%
  filter(!is.na(temp_adcp),
         date >= ymd("2018-07-01") & date < ymd("2018-08-01")) %>%
  mutate(date=as.Date(date)) %>%
  select(date_time, temp_adcp)

adcp_event <- adcp_daily %>%
  left_join(mko_mhw, by=c("date_time"="t")) %>%
  fill(event, threshCriterion) %>%
  select(date_time, temp_adcp, event, threshCriterion)

#m <- 
ggplot(adcp_event, aes(x = date_time, y=temp_adcp, color=threshCriterion, group=factor(c(0, cumsum(abs(head(threshCriterion, -1) != tail(threshCriterion, -1))))))) +
  geom_line(aes(linetype=threshCriterion), alpha=0.9, size=0.7) +
  scale_x_datetime(date_labels = "%b %d",
                   breaks = scales::date_breaks("1 week"),
                   expand=c(0,0),
                   limits = c(min(adcp_daily$date_time),
                              max(adcp_daily$date_time))) +
  scale_y_continuous(limits = c(12, 19), breaks = seq(12, 19, by = 2)) +
  scale_linetype_manual(values = c("solid", "longdash"),
                        guide = "none") +
  scale_color_manual(values = c("#000000","#D55E00"),
                      labels= c("No", "Yes")) +
  labs(y = expression(paste("Temperature (", degree, "C)")),
       x = "Date",
       color = "Marine heatwave threshold") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, vjust = 1, hjust=1, size=14),
        axis.text.y=element_text(size=14),
        axis.title.x=element_text(size=18),
        axis.title.y=element_text(size=18),
        legend.position="top")

#ggsave(here("experiment", "figures", "mhw_month.png"), width=12, height=6) #or width = 8
```

#Plot the different timeframes together
```{r}
ggarrange(y + theme(axis.title.x = element_blank()),
          m + theme(axis.title.x = element_blank()), 
          #labels = c("MKO", "ARQ"),
  common.legend = FALSE, legend = "bottom",
  ncol = 1, nrow = 2, 
  label.x=0.05, label.y=0.95, font.label=list(color="black",size=20))

#ggsave(here("experiment", "figures", "mhw_both.png"), width=14, height=7)
```

