---
title: "RPi ALL data visualization - For METHODS paper"
author: "Amelia Ritger"
date: "2023-08-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(lubridate)
library(janitor)
```

#ONLY KEEP DATA SINCE 03/13 11:00:00 (that's when I fixed the PID loop)
#I did a small PID loop adjustment at 13:00:00 but it shouldn't significantly affect the plot

# Load data and merge all temp files
```{r, message=FALSE, warning=FALSE}
rm(list = ls())
#temp_files <- list.files(here("experiment", "data", "rpi"), pattern=".*csv")
temp_files <- list.files(here("experiment", "code", "python", "methodsPub", "external"), pattern=".*csv")
temp_all <- data.frame()

for (i in 1:length(temp_files)){
  print(temp_files[i])
  temp_data <- read_csv(here("experiment", "code", "python", "methodsPub", "external", temp_files[i])) #each file will be read in, specify which columns you need read in to avoid any error
  temp_all <- rbind(temp_all, temp_data) #for each iteration, bind the new data to the building dataset
}

temp_all <- temp_all %>%
  clean_names() %>%
  select(1:8)
```

# Plot tank temps
```{r}
temp_clean <- temp_all %>%
  mutate(timestamp = ymd_hms(timestamp)) %>%
  select(!last_col(offset=1):last_col(), #%>% #remove hot/cold tank temps
         -heater_status) %>%
  pivot_longer(cols=3:5, names_to = "sensor", values_to = "temperature") %>%
  filter(timestamp > ymd_hms("2024-03-13 11:00:00"))

ggplot(temp_clean, aes(x=timestamp)) +
  geom_line(aes(y=temperature, color=sensor), size=1) +
  geom_line(aes(y=temp_set), color="black")
```


```{r}
temp_avg <- temp_all %>%
  mutate(timestamp = ymd_hms(timestamp)) %>%
  select(!last_col(offset=1):last_col()) %>%
  pivot_longer(cols=4:6, names_to = "sensor", values_to = "temperature") %>%
  group_by(timestamp, temp_set, heater_status) %>%
  summarise(avg_temp = mean(temperature)) %>%
  ungroup() %>%
  filter(timestamp > ymd_hms("2024-03-13 21:00:00"))

temp_five <- temp_all %>%
  mutate(timestamp = ymd_hms(timestamp),
         timestamp = floor_date(timestamp, "1 minute")) %>%
  select(!last_col(offset=1):last_col()) %>%
  pivot_longer(cols=4:6, names_to = "sensor", values_to = "temperature") %>%
  group_by(timestamp, temp_set) %>%
  summarise(avg_temp = mean(temperature)) %>%
  ungroup() %>%
  filter(timestamp > ymd_hms("2024-03-13 11:00:00"))
  
ggplot(temp_five, aes(x=timestamp)) +
  geom_line(aes(y=avg_temp), color="#0072B2", size=1) +
  geom_line(aes(y=temp_set), color="#000000", size=1, alpha=0.7)
  #geom_point(aes(y=avg_temp, color=heater_status), size=2) +

#ggsave(here("figures", "chill-old-new.png"))
```