---
title: "RPi ALL data visualization"
author: "Amelia Ritger"
date: "2023-08-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(lubridate)
library(janitor)
library(ggpubr)
library(svglite) #save vector figures
```

# Load data and merge all temp files
```{r}
rm(list = ls())
temp_files <- list.files(here("experiment", "data", "rpi"), pattern=".*csv")
temp_all <- data.frame()
for (i in 1:length(temp_files)){
  print(temp_files[i])
  temp_data <- read_csv(here("experiment", "data", "rpi", temp_files[i])) #each file will be read in, specify which columns you need read in to avoid any error
  temp_all <- rbind(temp_all, temp_data) #for each iteration, bind the new data to the building dataset
}
temp_all <- temp_all %>%
  clean_names() %>%
  select(1:25)

if(FALSE){
type1_files <- list.files(here("experiment", "data", "rpi", "type1"), pattern=".*csv")
temp_1 <- data.frame()
for (i in 1:length(type1_files)){
  print(type1_files[i])
  temp_data <- read_csv(here("experiment", "data", "rpi", "type1", type1_files[i])) #each file will be read in, specify which columns you need read in to avoid any error
  temp_1 <- rbind(temp_1, temp_data) #for each iteration, bind the new data to the building dataset
}
temp_1 <- temp_1 %>%
  select(1:22) %>%
  mutate(chill_heater = "NA", 
         severe_heater = "NA",
         extreme_heater = "NA") %>%
  select(1:4, 23:25, 5:22)

type2_files <- list.files(here("experiment", "data", "rpi", "type2"), pattern=".*csv")
temp_2 <- data.frame()
for (i in 1:length(type2_files)){
  print(type2_files[i])
  temp_data <- read_csv(here("experiment", "data", "rpi", "type2", type2_files[i])) #each file will be read in, specify which columns you need read in to avoid any error
  temp_2 <- rbind(temp_2, temp_data) #for each iteration, bind the new data to the building dataset
}
temp_2 <- temp_2 %>%
  select(1:19) %>%
  mutate(chill_set = "0",
         severe_set = chill_set,
         extreme_set = chill_set,
         chill_heater = "NA", 
         severe_heater = "NA",
         extreme_heater = "NA") %>%
  select(1, 20:25, 2:19)
}
```

# Plot tank temps
```{r}
# Assign treatments to each temperature probe
chill = c("x28_00000eb5045f","x28_00000eb3fd89","x28_00000eb42add","x28_00000eb51050","x28_00000eb4cb62")
severe = c("x28_00000eb50e10","x28_00000eb501b0", "x28_00000eb496d2", "x28_00000eb3cf7d", "x28_00000eb52c32")
extreme = c("x28_00000ec23ab6","x28_00000ec25534","x28_00000eb4b7e0", "x28_00000ec24f93", "x28_00000eb4619b")

sensors <- data.frame(
  tank = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15),
  sensor = c("x28_00000eb4cb62","x28_00000eb51050","x28_00000eb42add","x28_00000eb3fd89","x28_00000eb5045f",
             "x28_00000eb52c32", "x28_00000eb3cf7d", "x28_00000eb501b0", "x28_00000eb50e10","x28_00000eb496d2",
             "x28_00000eb4619b","x28_00000eb4b7e0","x28_00000ec24f93","x28_00000ec25534","x28_00000ec23ab6")
)

temp_clean <- temp_all %>%
  select(1:7, 8:25) %>%
  mutate(timestamp = ymd_hms(timestamp),
         severe_set = ifelse(timestamp < ymd_hms("2023-10-04 12:15:00"), chill_set, severe_set),
         extreme_set = ifelse(timestamp < ymd_hms("2023-10-04 12:15:00"), chill_set, extreme_set)) %>%
  select(-(last_col(offset=2):last_col()), #%>% #remove sump tank temps
         -(c(5:7))) %>% #%>% #remove heater status
  pivot_longer(cols=5:19, names_to = "sensor", values_to = "temperature") %>%
  filter(timestamp > ymd_hms("2023-09-21 12:00:00")) %>% #only keep data since addition of Corynactis
  #filter(timestamp > ymd_hms("2024-01-20 01:00:00"))
  mutate(treatment = case_when(
    sensor %in% chill ~ "chill",
    sensor %in% severe ~ "severe",
    sensor %in% extreme ~ "extreme",
    TRUE ~ "unknown"
  ),
    treatment = factor(treatment, levels = c("chill", "severe", "extreme"))) %>%
  merge(sensors, by = "sensor") #merge with sensors

plot_set <- ggplot(temp_clean, aes(x=timestamp)) +
  geom_line(aes(y=chill_set, color="chill_set")) +
  geom_line(aes(y=severe_set, color="severe_set")) +
  geom_line(aes(y=extreme_set, color="extreme_set")) +
  scale_color_manual(name = "",
                     breaks = c("chill_set", "severe_set", "extreme_set"),
                     values = c("chill_set" = "#003D52", "severe_set" = "#C28200", "extreme_set" = "#A53E00"),
                     labels = c("chill_set" = "Ambient Set Point", "severe_set" = "Severe Set Point", "extreme_set" = "Extreme Set Point")) +
  scale_y_continuous(breaks = seq(12, 26, 2), limits = c(12, 27)) +
  theme_minimal() +
  labs(x = "Date",
       y = "Temperature") +
  theme(legend.position = "top",
        text = element_text(size = 20))
```

# Plot tank temps averaged across treatments
```{r}
temp_sorted <- temp_clean %>%
  group_by(timestamp, chill_set, severe_set, extreme_set, treatment) %>%
  summarize(avg_temp = mean(temperature, na.rm=TRUE)) %>%
  ungroup() %>%
  filter(timestamp > ymd_hms("2023-09-22 12:00:00"),
         timestamp < ymd_hms("2024-02-21 10:00:00")) #remove first 24 hours after addition of Corynactis because temperature fluctuations as I was messing around with heaters/chillers

ggplot(temp_sorted, aes(x=timestamp)) +
  #geom_line(aes(y=chill_set, color="chill_set"), linetype="dashed") +
  #geom_line(aes(y=severe_set, color="severe_set"), linetype="dashed") +
  #geom_line(aes(y=extreme_set, color="extreme_set"), linetype="dashed") +
  geom_line(aes(y=avg_temp, color=treatment)) +
  scale_color_manual(name = "",
                     values = c("chill" = "#0072B2", "severe" = "#E69F00", "extreme" = "#D55E00"),
                     labels = c("chill" = "Control", "severe" = "Severe MHW", "extreme" = "Extreme MHW")) +
#  scale_color_manual(name = "Treatment",
#                     values = c("chill" = "#0072B2", "severe" = "#E69F00", "extreme" = "#D55E00",
#                                "chill_set" = "#003D52", "severe_set" = "#C28200", "extreme_set" = "#A53E00"),
#                     labels = c("chill" = "Ambient", "severe" = "Severe MHW", "extreme" = "Extreme MHW",
#                                "chill_set" = "Ambient Set Point", "severe_set" = "Severe Set Point", "extreme_set" = #"Extreme Set Point"),
#                     guide=guide_legend(override.aes = list(keyheight=10,alpha=1))) +
  scale_y_continuous(breaks = seq(12, 26, 2), limits = c(12, 27)) +
  theme_bw() +
  labs(x = "Date",
       y = "Temperature") +
  theme(legend.position = "top",
        text = element_text(size = 20))

ggsave(here("experiment", "figures", "WSN","avg_temps.png"), width=12, height=7)
#image <- ggarrange(plot_set, plot_avg, ncol = 1)
#ggsave(file = here("experiment", "figures", "WSN","avg_temps.svg"), plot = image, width=12, height=9)
```

# Plot tank temps for each tank
```{r}
temp_clean <- temp_clean %>%
  mutate(tank = as.factor(tank)) %>%
  filter(timestamp < ymd_hms("2024-02-21 10:00:00"))

plot_tank <- ggplot(temp_clean, aes(x=timestamp)) +
  #geom_line(aes(y=chill_set, color="chill_set"), linetype="dashed") +
  #geom_line(aes(y=severe_set, color="severe_set"), linetype="dashed") +
  #geom_line(aes(y=extreme_set, color="extreme_set"), linetype="dashed") +
  geom_line(aes(y=temperature, color=tank), alpha=0.5) +
  scale_color_manual(name = "",
                     values = c("1" = "#005B8C", "2" = "#0072B2", "3" = "#0085D1", "4" = "#0099E6", "5" = "#00B2FF", "6" = "#E69F00","7" = "#F1C232","8" = "#F39C11","9" = "#FCD700","10" = "#D68A00", "11" = "#D55E00","12" = "#E84C00","13" = "#D64541","14" = "#F44336","15" = "#E67200")) +
                     #values = c("chill" = "#0072B2", "severe" = "#E69F00", "extreme" = "#D55E00")
                     #labels = c("chill" = "Ambient Treatment", "severe" = "Severe MHW", "extreme" = "Extreme MHW")) +
#  scale_color_manual(name = "Treatment",
#                     values = c("chill" = "#0072B2", "severe" = "#E69F00", "extreme" = "#D55E00",
#                                "chill_set" = "#003D52", "severe_set" = "#C28200", "extreme_set" = "#A53E00"),
#                     labels = c("chill" = "Ambient", "severe" = "Severe MHW", "extreme" = "Extreme MHW",
#                                "chill_set" = "Ambient Set Point", "severe_set" = "Severe Set Point", "extreme_set" = #"Extreme Set Point"),
#                     guide=guide_legend(override.aes = list(keyheight=10,alpha=1))) +
  scale_y_continuous(breaks = seq(12, 26, 2), limits = c(12, 27)) +
  theme_minimal() +
  labs(x = "Date",
       y = "Temperature",
       color = "Tank") +
  theme(legend.position = "top")

image <- ggarrange(plot_set, plot_tank, ncol = 1)

#ggsave(file = here("experiment", "figures", "WSN","tank_temps.svg"), plot = image, width=12, height=9)
```


# Extract weekly average temperature for each tank
```{r}
start_date <- as.Date("2023-10-06")
fridays <- seq(from = start_date, to = as.Date("2024-02-21"), by = "week")
date_ranges <- data.frame(
  friday = fridays,
  start_date = fridays - 6,  # Saturday
  end_date = fridays          # Friday
)

#add a row to the dataframe 
#temp_sum <- rbind(temp_sum, data.frame(sensor = "x28_00000eb4cb62", tank = 1, timestamp = as.POSIXct("2023-12-28 12:01:10"), temperature = 1000, date = as.Date("2023-12-28"), chill_set=14.75, severe_set=14.75, extreme_set=14.75, treatment="chill"))

temp_sum <- temp_clean %>%
  arrange(timestamp, tank) %>%
  mutate(date = as.Date(timestamp)) %>%
  filter(date >= min(date_ranges$start_date) & date <= max(date_ranges$end_date)) %>%
  left_join(date_ranges, by = character()) %>%
  filter(date >= start_date & date <= end_date) %>%
  group_by(tank, treatment, friday) %>%
  summarize(avg_temp = mean(temperature, na.rm = TRUE), 
            min_temp = min(temperature, na.rm = TRUE),
            max_temp = max(temperature, na.rm = TRUE),
            .groups = 'drop')

#plot the temperatures for each tank
ggplot(temp_sum, aes(x = friday, y = avg_temp, color = as.factor(tank))) +
  geom_line() +
  geom_point() +
  #scale_color_manual(values = c("1" = "#0072B2", "2" = "#D55E00", "3" = "#009E73")) +
  labs(x = "Date",
       y = "Temperature") +
  theme_minimal()

#export temp_sum as .csv file
#write_csv(temp_sum, here("experiment", "data", "weekly_temperature.csv"))
```

# Extract 3-day lag average temperature for each tank
```{r}
date_sequence <- seq(from = as.Date("2023-09-25"), to = as.Date("2024-02-21"), by = "day")
tuesdays_and_fridays <- date_sequence[weekdays(date_sequence) %in% c("Tuesday", "Friday")]

#add a row to the dataframe 
#temp_check <- rbind(temp_clean, data.frame(sensor = "x28_00000eb4cb62", tank = 1, timestamp = as.POSIXct("2023-10-10 12:01:10"), temperature = 100000, chill_set=14.75, severe_set=14.75, extreme_set=14.75, treatment="chill"))

temp_sum_biweek <- temp_clean %>%
  arrange(timestamp, tank) %>%
  mutate(date = as.Date(timestamp)) %>%
  filter(date >= min(tuesdays_and_fridays) & date <= max(tuesdays_and_fridays)) %>%
  group_by(tank, treatment, date) %>%
  summarize(avg_temp = mean(temperature, na.rm = TRUE), 
            min_temp = min(temperature, na.rm = TRUE),
            max_temp = max(temperature, na.rm = TRUE),
            .groups = 'drop') %>%
  ungroup() %>%
  group_by(tank) %>%
  mutate(avg_temp_last_3_days = zoo::rollmean(avg_temp, k = 3, fill = NA, align = "right"),
         min_temp_last_3_days = zoo::rollapply(avg_temp, width = 3, FUN = min, fill = NA, align = "right"),
         max_temp_last_3_days = zoo::rollmax(avg_temp, k = 3, fill = NA, align = "right")) %>%
  ungroup() %>%
  filter(date %in% tuesdays_and_fridays,
         date > as.Date("2023-09-28"))

#write_csv(temp_sum_biweek, here("experiment", "data", "three_day_temperature.csv"))
```

Make temperature plot
```{r}

```


