---
title: "RPi data visualization"
author: "Amelia Ritger"
date: "2023-08-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(lubridate)
library(janitor)
library(quantmod) # to calculate frequency of oscillation
```

```{r}
profile <- read_csv(here("data", "mhw_profile_final.csv")) %>%
  filter(date_time < ymd_hms("2015-10-15 23:00:00")) %>%
  filter(date_time > ymd_hms("2015-09-15 01:00:00")) %>%
  select(1:4)
  #mutate(timestamp = date_time %m+% years(8),
  #       temperature=chill)

ggplot(profile, aes(x = date_time)) +
  geom_line(aes(y = temp, colour="temp"), size = 0.8) +
  geom_line(aes(y = chill, colour="chill"),size = 0.8) +
  geom_line(aes(y = extreme, colour="extreme"),size = 0.8) +
  scale_colour_manual(name = "Line Colour",
                      values = c("temp" =  "red",
                                 "chill" = "dodgerblue4", 
                                 "extreme" =  "darkred"),
                      labels= c("Severe", "Chill", " Extreme")) +
  scale_x_datetime(date_labels = "%b %d",
                   breaks = scales::date_breaks("3 days"),
                   expand = c(0, 0),
                   limits = c(min(profile$date_time),max = max(profile$date_time))) +
  scale_y_continuous(limits = c(13, 27), breaks = seq(13, 27, by = 2)) +
  guides(colour = guide_legend(override.aes = list(fill = NA))) +
  labs(y = expression(paste("Temperature (", degree, "C)")),x = "Date") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45,vjust = 1,hjust = 1,size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),
        axis.title.y = element_text(size = 22),
        legend.text = element_text(size = 20),
        legend.position = "top",
        legend.title = element_blank())

```

# Plot all tank temps
```{r}
data <- read_csv(here("data", "2023-09-14 16:22:12.972213.csv")) %>%
  select(1:7, 8:25) %>%
  #select(1:7, 8:12) %>%
  clean_names() %>%
  mutate(timestamp = ymd_hms(timestamp)) %>%
  #select(-(c(3:7))) %>%
  #pivot_longer(cols=3:7, names_to = "sensor", values_to = "temperature") #5:19
  select(-(last_col(offset=3):last_col()), #%>% #remove sump tank temps
         -(c(5:7))) %>% #%>% #remove heater status
  #rowwise() %>%
  #mutate(avg_temp = mean(c_across(4:8))) %>%
  #ungroup() %>%
  #mutate(diff_temp = (.[[9]]-.[[2]])) %>%
  pivot_longer(cols=5:18, names_to = "sensor", values_to = "temperature")  %>%
  filter(timestamp > ymd_hms("2023-09-14 18:00:00"))

ggplot(data, aes(x=timestamp)) +
  geom_line(aes(y=temperature, color=sensor), size=1) +
  geom_line(aes(y=15), color="black") +
  geom_line(aes(y=18), color="black") +
  geom_line(aes(y=22), color="black") +
  scale_y_continuous(limits=c(21.75,22.3))
  #geom_line(aes(y=avg_temp), color="darkblue") +
  #geom_point(aes(y=diff_temp, color = chill_heater), size=1)

ggsave(here("figures", "higherpid.png"))
```

# Plot the sump tank temps
```{r}
sump_all <- read_csv(here("data", "2023-09-14 16:22:12.972213.csv")) %>%
  select(1:7, 23:25) %>%
  clean_names() %>%
  mutate(timestamp = ymd_hms(timestamp)) %>%
  rename(severe =8,
         extreme = 9,
         chill =10) %>%
  mutate(diff_severe = severe-severe_set,
         diff_extreme = extreme-extreme_set, # + 24,
         diff_chill = chill-chill_set)
  
ggplot(sump_all, aes(x=timestamp)) +
  geom_point(aes(y=extreme, color=extreme_heater)) +
  geom_point(aes(y=severe, color=severe_heater)) +
  geom_point(aes(y=chill, color=chill_heater)) +
  geom_line(aes(y=15), color="black") +
  geom_line(aes(y=18), color="black") +
  geom_line(aes(y=22), color="black")

  geom_line(aes(y=chill_set), color="black", size=0.5) +
  geom_line(aes(y=severe_set), color="black", size=0.5) +
  geom_line(aes(y=extreme_set), color="black", size=0.5) #+
  geom_point(aes(y=diff_extreme, color=extreme_heater), size=1)

```

#plot sump tank comparison with experimental tank data (to check treshold differential value)
## Severe tanks
```{r}
sump_tank <- read_csv(here("data", "2023-09-14 16:22:12.972213.csv")) %>%
  select(1:7, 8:25) %>%
  clean_names() %>%
  mutate(timestamp = ymd_hms(timestamp)) %>%
  select(-(last_col(offset=1):last_col()),
         -(c(2,4:5, 7:12,18:22))) %>%
  rename(T1 =4,
         T2 =5,
         T3 =6,
         T4 =7,
         T5 =8,
         sump=9) %>%
  pivot_longer(cols=4:8, names_to = "sensor", values_to = "temperature") %>%
  rename(sump = 4) %>%
  mutate(diff = sump-severe_set)

ggplot(sump_tank, aes(x=timestamp)) +
  geom_line(aes(y=temperature, color=sensor), size=1) +
  #geom_point(aes(y=sump, color=severe_heater), size=0.5) +
  #scale_colour_manual(values=c("on"="red", "off"="blue")) +
  geom_line(aes(y=18), color="black")
  #geom_point(aes(y=diff), color="orange", size=1)
```


```{r}
severe_tank <- read_csv(here("data", "2023-09-14 16:22:12.972213.csv")) %>%
  select(1:7, 8:25) %>%
  clean_names() %>%
  mutate(timestamp = ymd_hms(timestamp)) %>%
  select(#-(last_col(offset=1):last_col()),
         -(c(2:4,6:7, 13:24))) %>% #severe: c(2,4:5, 7:12,18:22)
  rename(T1 =4,
         T2 =5,
         T3 =6,
         T4 =7,
         T5 =3,
         sump=8) %>%
  filter(timestamp > ymd_hms("2023-09-14 18:00:00")) # %>%
  #rename(T1 =4,
  #       T2 =5,
  #       T3 =6,
  #       T4 =7,
  #       T5 =8,
  #       sump=9) %>%
  #select(-c(2:3)) %>%
  pivot_longer(cols=3:8, names_to = "tank", values_to = "temp")
  #ungroup()
  

ggplot(severe_tank, aes(x=timestamp)) +
  geom_line(aes(y=temp, color=tank), size=1)
  geom_point(aes(y=sump, color=chill_heater), size=0.5) +
  scale_colour_manual(values=c("on"="red", "off"="blue")) +
  geom_line(aes(y=chill_set), color="black") +
  geom_point(aes(y=diff), color="orange", size=1)

one <- severe_tank$T5
time <- seq(from=0, to=length(one)-1, by=1)
plot(time,one, type = "l", lty = 1)

find_peaks <- function (x, m = 3){
    shape <- diff(sign(diff(x, na.pad = FALSE)))
    pks <- sapply(which(shape < 0), FUN = function(i){
       z <- i - m + 1
       z <- ifelse(z > 0, z, 1)
       w <- i + m + 1
       w <- ifelse(w < length(x), w, length(x))
       if(all(x[c(z : i, (i + 2) : w)] <= x[i + 1])) return(i + 1) else return(numeric(0))
    })
     pks <- unlist(pks)
     pks
}

pk <- find_peaks(one, m = 7) #set a high threshold bc we need it...
diff_list <- diff(pk, lag=2) #period = 40 SEVERE, 41 CHILL

peaks <- severe_tank %>%
  arrange(timestamp) %>% #make sure observations are in order by date/time
  mutate(peak = ifelse(row_number() %in% c(pk) == TRUE, 1, 0)) #if a row ID matches the row ID found by find_peaks, then call it "1" (if not, "0")

ggplot(peaks, aes(x=timestamp)) +
  geom_point(aes(y=T5, color=peak), size=1) +
  #geom_point(aes(y=sump, color=severe_heater), size=0.5) +
  #scale_colour_manual(values=c("on"="red", "off"="blue")) +
  geom_line(aes(y=15), color="black")
  #geom_point(aes(y=diff), color="orange", size=1)
```


## Chill tanks
```{r}
sump_tank <- read_csv(here("data", "2023-09-13 16:23:34.257618.csv")) %>%
  select(1:7, 8:25) %>%
  clean_names() %>%
  mutate(timestamp = ymd_hms(timestamp)) %>%
  select(-(c(3:4, 6:7, 13:24))) %>%
  pivot_longer(cols=4:8, names_to = "sensor", values_to = "temperature") %>%
  rename(sump = 4) %>%
  mutate(diff = sump-chill_set) # %>%

ggplot(sump_tank, aes(x=timestamp)) +
  geom_line(aes(y=temperature, color=sensor), size=1) +
  geom_point(aes(y=sump, color=chill_heater), size=0.5) +
  scale_colour_manual(values=c("on"="red", "off"="blue")) +
  geom_line(aes(y=chill_set), color="black") +
  geom_point(aes(y=diff), color="orange", size=1)
```

## Extreme tanks
```{r}
sump_tank <- read_csv(here("data", "2023-09-13 16:23:34.257618.csv")) %>%
  select(1:7, 8:25) %>%
  clean_names() %>%
  mutate(timestamp = ymd_hms(timestamp)) %>%
  select(-(c(2:3, 5:6, 8:17, 23, 25))) %>%
  pivot_longer(cols=4:8, names_to = "sensor", values_to = "temperature") %>%
  rename(sump = 4) %>%
  mutate(diff = sump-extreme_set) # %>%

ggplot(sump_tank, aes(x=timestamp)) +
  geom_line(aes(y=temperature, color=sensor), size=1) +
  geom_point(aes(y=sump, color=extreme_heater), size=0.5) +
  scale_colour_manual(values=c("on"="red", "off"="blue")) +
  geom_line(aes(y=extreme_set), color="black") 
```

```{r}
data <- read_csv(here("data", "2023-08-31 15:17:07.635884.csv")) %>%
  select(1:22) %>%
  clean_names() %>%
  mutate(timestamp = ymd_hms(timestamp)) %>%
  rename(T1 = 10,
         T2 =11,
         T3 =12,
         T4 = 13,
         T5 =14) %>%
  select(1,2,10:14) %>%
  pivot_longer(cols=3:6, names_to = "tank", values_to = "temperature")


ggplot(data) +
  geom_line(aes(x=timestamp, y=temperature, color=tank), size=1) +
  geom_line(aes(x=timestamp, y=chill_set), color="black")

#ggsave(here("figures", "bad.png"))
```


