---
title: "Looking at MHW trends in the SBC LTER to inform the MHWsim experiment"
author: "Amelia Ritger"
date: "2023-07-31"
output: html_document
---

#Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(scales) #date_format for x axis plot
library(heatwaveR)
library(ggpubr) #combine multiple ggplots
```

Datafiles to download from SBC LTER: 
mohawk_mooring_mko_20230608.csv
naples_mooring_nap_20230608.csv

#Load data
```{r}
temp_raw <-  read_csv(here("data", "naples_mooring_nap_20230608.csv"), col_names = TRUE) %>%
  select(year, month, day,  decimal_time, Temp_adcp, Temp_top, Temp_mid, Temp_bot,  ADCP_depth) %>%
  clean_names()
```

#Clean up the data
```{r}
temp_clean <- temp_raw %>%
  unite("date", "year", "month", "day", sep=" ", remove=FALSE) %>%
  mutate(date=ymd(date)) %>% #apply lubridate to date
  arrange(date, decimal_time)# %>%
  #mutate(time=dminutes(decimal_time))

temp_clean <- temp_clean %>%
  mutate(source = "adcp",
         source = ifelse(temp_adcp>999,"bottom",source),
         temp=ifelse(temp_adcp>999,temp_bot,temp_adcp),
         source = ifelse(temp>999,"middle",source),
         temp=ifelse(temp>999,temp_mid,temp),
         source = ifelse(temp>999,"top",source),
         temp=ifelse(temp>99,temp_top,temp)) %>%
  filter(temp<999)

#ggplot(temp_clean, aes(x=date, y=temp)) +
#  geom_point()
```

#Get monthly average temperature for each month across years
```{r}
mhw_sum <- temp_clean %>%
  group_by(year, month) %>%
  summarize(temp=mean(temp)) %>%
  filter(month > 7 | month < 3) %>%
  mutate(year=as.factor(year),
         month=as.factor(month),
         month=fct_relevel(month,c("8","9","10","11","12","1","2")))

ggplot(mhw_sum, aes(x=month, y=temp, group=year)) +
  geom_point(aes(color=year)) +
  geom_line(aes(color=year)) +
  labs(title="Average temperature for each month")

#ggsave(here("figures", "avg_temp_mko.png"))
```

#Look at extremes - highs and lows - over time
```{r}
max_temp <- max(temp_clean$temp)
min_temp <- min(temp_clean$temp)

temp_top <- temp_clean %>%
  filter(temp>20)

temp_high <- temp_clean %>%
  group_by(year, month) %>%
  summarize(temp=max(temp)) %>%
  filter(month > 7 | month < 3) %>%
  mutate(year=as.factor(year),
         month=as.factor(month),
         month=fct_relevel(month,c("8","9","10","11","12","1","2")))

ggplot(temp_high, aes(x=month, y=temp, group=year)) +
  geom_point(aes(color=year)) +
  geom_line(aes(color=year)) +
  labs(title="Hottest temperature for each month")

#ggsave(here("figures", "max_temp_mko.png"))
```

## Assess MHW
```{r}
# Reformat to run heatwaveR
temp_heatwaver <- temp_clean %>%
  group_by(date) %>%
  summarize(temp=mean(temp)) %>%
  mutate(t=as.Date(date)) %>%
  select(t, temp)

#identify start and end dates of df
head(temp_heatwaver)
tail(temp_heatwaver)

start_date <- "2001-02-14" #CHECK VALUES MANUALLY
end_date <- "2023-04-11" #CHECK VALUES MANUALLY

# Detect the events in a time series
ts <- heatwaveR::ts2clm(temp_heatwaver, x=t, y=temp, climatologyPeriod = c(start_date, end_date))
mhw <- heatwaveR::detect_event(ts)
```

Identify MHW events
```{r}
mhw_event <- mhw$event %>%
   dplyr::ungroup() %>%
   dplyr::select(event_no, duration, date_start, date_peak, date_end, intensity_max, intensity_mean, intensity_cumulative, rate_onset, rate_decline) %>%
  filter(date_start > ymd("2013-08-01")) %>% #Only look at MHWs in the last decade
  mutate(month_start=month(date_start),
         month_end=month(date_end)) %>%
  filter(between(month_start,1,2) | between(month_start,8,12)) %>% #CHECK MANUALLY BEFORE FILTERING
  dplyr::arrange(-duration) %>%
  select(1:10)

#write_csv(mhw_event, here("tables", "mohawk_mhw_all.csv"))
```

Get 95% quantile and average values of duration, intensity
```{r}
duration_95 <- unname(quantile(mhw_event$duration, c(.95)))
duration_mean <- mean(mhw_event$duration)

intensity_95 <- unname(quantile(mhw_event$intensity_max, c(.95)))
intensity_mean <- mean(mhw_event$intensity_max)

mhw_summary <- data.frame(Metric=c("Duration", "Max intensity"),
                          Percentile_95=c(duration_95,intensity_95),
                          Mean=c(duration_mean,intensity_mean))

#write_csv(mhw_summary, here("tables", "mohawk_mhw_summary.csv"))
```

# Plot it all up
```{r}
#identify dates of interest
climatology <- mhw$climatology %>%
  arrange(t)

mhw_start <- which(climatology$t == "2013-08-01")[1]
mhw_end <- which(climatology$t == end_date)[1]

#subset for dates of interest
mhw_subset <- mhw$climatology %>%
  slice(mhw_start:mhw_end) %>%
  mutate(month=as.factor(month(t))) 

#Create a df of dates to shade the time period of interest in ggplot
dateRanges <- data.frame(
  start = seq(ymd("1900-08-01"), ymd("2100-08-01"), "1 year"),
  end = seq(ymd("1901-02-01"), ymd("2101-02-01"), "1 year")
)

#plot clean ribbon
ggplot(mhw_subset, aes(x = t, ymax = pmax(thresh, temp), ymin = thresh)) +
  geom_rect(data = dateRanges, aes(xmin = start , xmax = end, ymin = -Inf, ymax = Inf),
            inherit.aes=FALSE, alpha = 0.4, fill = c("lightgrey"))+
  geom_line(aes(y = seas, colour = "seas"), size = 0.8) +
  geom_ribbon(fill = "red") +
  geom_line(aes(y = thresh, colour = "thresh"), size = 0.8) +
  geom_line(aes(y = temp, colour = "temp"), alpha=0.3) +
  scale_colour_manual(name = "Line Colour",
                      values = c("seas" = "dodgerblue4",
                                 "temp" = "black", 
                                 "thresh" =  "chartreuse4"),
                      labels= c("Climatology", "Temperature", "Threshold")) +
  scale_x_date(date_labels = "%b %Y",
               breaks = scales::date_breaks("6 months"),
               expand=c(0,0),
               limits = c(min(mhw_subset$t), 
                         max = max(mhw_subset$t))) +
  scale_y_continuous(limits = c(10, 22), breaks = seq(10, 22, by = 2)) +
  guides(colour = guide_legend(override.aes = list(fill = NA))) +
  labs(y = expression(paste("Temperature (", degree, "C)")),
       x = "Date") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, vjust = 1, hjust=1, size=14),
        axis.text.y=element_text(size=14),
        axis.title.x=element_text(size=18),
        axis.title.y=element_text(size=18),
        legend.text=element_text(size=12),
        legend.position="top",
        legend.title = element_blank())

#ggsave(here("figures", "mhw_plot_nap.png"), width = 20, height = 7)
```
